Update static config
UML-Cyber-Security/CCDC_Practice_Infrastructure pull request #101
Opened 2024-11-07 01:30 UTC by DaintyJet

## Overview of Changes

Updated Linux Static Configuration Documents (standalone) and the Harvester Document to refer to routes and DNS configuration as creating internal networks often requires this.

## Reason for Modification

This cleans up some of the old documentation (marginally) and it updates the new Harvester docs with additional information that may be helpful.

## Verification

- [ ] The documentation is completed, or does not contain work-in-progress/partially-completed sections.
- [ ] The documentation is written in *Markdown* (Exception for Inject and Incident Reports).
- [ ] Any Images are contained in a subdirectory `Images`.
- [ ] Any scripts, Ansible Playbooks, Terraform scripts, etc. Have documentation explaining their purpose and use case.
- [ ] Any scripts are tested.
- [ ] I have assigned and notified a reviewer.

2024-11-07 01:31 UTC, DaintyJet commented
Please DO NOT merge till others I have requested reviewed this.

2024-11-07 16:49 UTC, ryanwiddop reviewed
This looks good to me

2024-11-08 17:26 UTC, P-rple commented on Admin/Infrastructure/Harvister/Network Creation/README.md
>  In the *Route* window configure it to use the **Manual** mode so we can make this network *internal* and not able to immediately access the internet. Fill in a `CIDR` range that does not conflict wit
I would add, how can someone determine and confirm the host's network CIDR range?
For the purpose of longevity of this document, in the event it ever changes.

2024-11-08 20:34 UTC, P-rple commented on Admin/Infrastructure/Harvister/Network Creation/README.md
> +>     macaddress: MACADDR
Make a note that "MACADDR" is a placeholder for an actual mac address
"FF:FF:FF:FF:FF:FF"

2024-11-08 20:35 UTC, P-rple requested changes
I've added some simple suggestions.

2024-11-08 20:45 UTC, P-rple requested changes
Fix number bullet point

2024-11-08 20:45 UTC, P-rple commented on OperatingSystem-Services/Platform-Linux/Static-Config/README.md
> +1. Click *add* and fill out the information.
Is this supposed to be 6. instead of 1.

2024-12-09 19:33 UTC, P-rple approved these changes

2024-12-21 22:19 UTC, merged