Declanb branch
UML-Cyber-Security/CCDC_Practice_Infrastructure pull request #108
Opened 2024-12-12 21:38 UTC by DecBat

## Overview of Changes

General overview of what has been changed:

Under Linux based services I have added KeyCloak documentation which falls under identity management. This documentation is not fully complete but should walk through KeyCloak up untill access of the main page. There is also a start on the dns documentation albeit very brief I though I may as well include it, feel free to deny it or accept it which ever makes the most sense, but I will continue working on it for sure.

## Reason for Modification

There was no documentation on KeyCloak so I decided to make some. There is very little on dns in the repository so I decided to comb through my experience with it and create documentation for future use and ease.

## Verification

- [ ] The documentation is completed, or does not contain work-in-progress/partially-completed sections.
- [ ] The documentation is written in *Markdown* (Exception for Inject and Incident Reports).
- [ ] Any Images are contained in a subdirectory `Images`.
- [ ] Any scripts, Ansible Playbooks, Terraform scripts, etc. Have documentation explaining their purpose and use case.
- [ ] Any scripts are tested.
- [ ] I have assigned and notified a reviewer.

2024-12-12 21:39 UTC, DecBat commented
My first time virtually making any pull request in git as well so let me know if there is anything that I should have done beforehand, thank you.

2024-12-13 02:10 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
How the mighty have fallen... :(

Capitalize services (aka Docker).

Usually, it's helpful to put commands in single ticks around it so that it shows up like `this`. It'll make it easier to understand that this is something that you'll want to do within the software you're using.

I'll accept the WIP work for now. Just fix those capitalization things primarily. Otherwise, it's good. Maybe add a section to install baremetal (i.e. not with Docker)? Not completely necessary, but just a recommendation if you wanted to.

2024-12-13 02:12 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Windows/DNS/DNS.md
I would say separate into more paragraphs (maybe a small bulleted list summary). It seems like a wall of text at this point. Did you want to highlight something about it, or just have this wall of text. The use for CCDC could be in its own section. Not a bad idea.

2024-12-13 02:13 UTC, ChrisM09 requested changes
Almost. Just the capitalization and some grammar checks are needed. I'd recommend putting it into something like Grammarly or even use Mr. G to proofread it.

2024-12-30 22:31 UTC, DaintyJet requested changes
Slight rewording as suggested by Chris. Also the replacements to make all instances of `docker` to be capital `Docker` makes some of the commands broken.

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +sudo apt install Docker-ce
I am not sure if this is fine; check if package names are case-sensitive. As far as I am aware they may not be.

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +sudo systemctl start Docker
Services are case sensitive. Capital D docker will not work.

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +Docker --version
Commands are case sensitve. This should be lower case

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +Below is the squential command lines needed to download and install Docker, more in depth documentation on the workings of Docker should be found elsewhere on this repo.
Probably reword a little bit:

```suggestion
Use the following commands to install Docker, we will be leveraging the advantages of containerization in this deployment. Additional details on Docker and other containerization platforms can be found elsewhere in this repository. 
```

maybe want to mention something about how other container engines will require different steps that are not covered in something like a NOTE block
```
> [!NOTE]
> words
```

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +sudo apt install Docker-ce
Same this elsewhere throughout

2024-12-30 22:31 UTC, DaintyJet commented on OperatingSystem-Services/Platform-Linux/Identity Management/KeyCloak/KeyCloak.md
> +Once you have installed Docker you will be able to run and start it with the following commands
I think you could replace it with one command `systemctl enable --now docker` if you want

2025-01-11 17:47 UTC, DaintyJet reviewed
Fixed some small Spelling Mistakes, and added Note Tags.

Waiting on Chris to review since he had requested some changes

2025-01-12 03:36 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Windows/0-Scripts/Auto/disabling_accounts.ps1
Just a scary script. There have been winrm checks before.

2025-01-12 03:41 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Windows/DNS/DNS.md
Typo: DNS = Domain Name System

2025-01-12 03:42 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Windows/DNS/AD Integration
Blank file?

2025-01-12 03:43 UTC, ChrisM09 requested changes
The main one was the typo for DNS definition. 

I was about to let the empty file go but now since I'm requesting some changes, then we'll just get rid of it.

So close though!

2025-01-18 00:26 UTC, ChrisM09 requested changes
Just the one thing. Everything else is fine

2025-01-18 00:26 UTC, ChrisM09 commented on OperatingSystem-Services/Platform-Windows/DNS/DNS.md
DNS definition still incorrect.

2025-01-18 18:26 UTC, ChrisM09 approved these changes
LGTM. Discussed firewall portion of script offline (allowing access to RDP, WinRM in this script before enabling firewall). Moving to new pull request. This is all set.

2025-01-18 18:46 UTC, DaintyJet approved these changes

2025-01-18 19:50 UTC, merged